
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: text-to-speech
    version: v2
  name: text-to-speech-canary
  namespace: apps
spec:
  selector:
    matchLabels:
      app: text-to-speech
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: text-to-speech 
        version: v2   
    spec:
      containers:
        - name: text-to-speech
          image: babbili/text-to-speech:py075b11e
          imagePullPolicy : Always       
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
          envFrom:
            - secretRef:
                name: sa-key
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
          - containerPort: 1323
      serviceAccount: text-to-speech
      serviceAccountName: text-to-speech
