
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: text-to-speech
  name: text-to-speech
  namespace: apps

---

apiVersion: v1
kind: Secret
metadata:
  name: text-to-speech-svca-token
  namespace: apps
  annotations:
    kubernetes.io/service-account.name: "text-to-speech"
type: kubernetes.io/service-account-token

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: text-to-speech 
    version: v1
  name: text-to-speech
  namespace: apps
spec:
  selector:
    matchLabels:
      app: text-to-speech
      version: v1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: text-to-speech 
        version: v1
    spec:
      containers:
        - name: text-to-speech
          image: babbili/text-to-speech:e3b4f2527
          imagePullPolicy : Always       
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
          envFrom:
            - secretRef:
                name: sa-key
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
          - containerPort: 1323
      serviceAccount: text-to-speech
      serviceAccountName: text-to-speech

---

apiVersion: v1
kind: Service
metadata:
  name: text-to-speech
  namespace: apps
  labels:
    app: text-to-speech
spec:
  type: ClusterIP
  selector:
    app: text-to-speech
  ports:
    - name: http
      port: 80
      targetPort: 1323
      protocol: TCP
